// WasmBindgen CLI Tool
// Generates Swift bindings from WIT files

import ArgumentParser
import Foundation
import WITParser
import SwiftBindgenCore

@main
struct WasmBindgenCLI: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "wasmkit-bindgen",
        abstract: "Generate Swift bindings from WIT interface definitions",
        version: "0.1.0"
    )
    
    @Option(name: .shortAndLong, help: "Directory containing WIT files")
    var witDir: String
    
    @Option(name: .shortAndLong, help: "Output directory for generated Swift files")
    var output: String
    
    @Flag(name: .long, help: "Generate WasmKit import providers")
    var withProviders = false
    
    @Flag(name: .long, inversion: .prefixedNo, help: "Use async/await in generated code")
    var async = true
    
    mutating func run() throws {
        let witURL = URL(fileURLWithPath: witDir)
        let outputURL = URL(fileURLWithPath: output)
        
        // Find all WIT files
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(at: witURL, includingPropertiesForKeys: nil) else {
            throw ValidationError("Cannot enumerate WIT directory: \(witDir)")
        }
        
        var witFiles: [URL] = []
        for case let fileURL as URL in enumerator {
            if fileURL.pathExtension == "wit" {
                witFiles.append(fileURL)
            }
        }
        
        if witFiles.isEmpty {
            print("No WIT files found in \(witDir)")
            return
        }
        
        print("Found \(witFiles.count) WIT files")
        
        // Create output directory
        try fm.createDirectory(at: outputURL, withIntermediateDirectories: true)
        
        // Configure generator
        var config = SwiftGenConfig()
        config.useAsync = async
        config.generateImports = withProviders
        
        let protocolGen = SwiftProtocolGenerator(config: config)
        let registryGen = ImportRegistryGenerator(config: config)
        
        // Parse and generate
        var allOutput = fileHeader()
        
        for witFile in witFiles {
            print("Processing: \(witFile.lastPathComponent)")
            
            let source = try String(contentsOf: witFile, encoding: .utf8)
            
            // Lex
            var lexer = WITLexer(source: source)
            let tokens = try lexer.tokenize()
            
            // Parse
            var parser = WITParser(tokens: tokens)
            let document = try parser.parse()
            
            // Generate protocols
            allOutput += protocolGen.generate(from: document)
            
            // Generate providers if requested
            if withProviders {
                for item in document.items {
                    if case .interface(let iface) = item {
                        allOutput += registryGen.generateProvider(for: iface, package: document.package)
                    }
                }
            }
        }
        
        // Write output
        let outputFile = outputURL.appendingPathComponent("WASIBindings.swift")
        try allOutput.write(to: outputFile, atomically: true, encoding: .utf8)
        
        print("Generated: \(outputFile.path)")
    }
    
    private func fileHeader() -> String {
        """
        // AUTO-GENERATED from WIT files - DO NOT EDIT
        // Generated by wasmkit-bindgen
        // Regenerate by building the project or running: swift package plugin wasmkit-bindgen
        
        import Foundation
        import WasmKit
        
        // MARK: - WASI Error Type
        
        /// WASI error types with typed throws support
        public enum WASIError: Error, Sendable {
            case invalidDescriptor(Int32)
            case wouldBlock
            case streamClosed
            case accessDenied
            case noEntry
            case invalidArgument
            case notSupported
            case unknown(errno: Int32)
        }
        
        // MARK: - Import Provider Protocol
        
        /// Protocol for types that provide WASI imports
        public protocol WASIImportProvider {
            func register(into imports: inout Imports, store: Store, memory: @escaping () -> Memory?)
        }
        
        // MARK: - Memory Extension for reading
        
        extension Memory {
            func readString(offset: UInt, length: Int) -> String? {
                var bytes = [UInt8](repeating: 0, count: length)
                withUnsafeMutableBufferPointer(offset: offset, count: length) { buffer in
                    for i in 0..<length {
                        bytes[i] = buffer[i]
                    }
                }
                return String(bytes: bytes, encoding: .utf8)
            }
        }
        
        
        """
    }
}
