$schema: "https://moonrepo.dev/schemas/workspace.json"

projects:
  - "packages/*"
  - "frontend"
  - "worker"
  - "runtime"

vcs:
  client: git
  defaultBranch: main

hasher:
  optimization: "accuracy"
  ignoreMissingPatterns:
    - "**/.env*"
  ignorePatterns:
    - "**/*.md"
    - "**/LICENSE*"
    - "**/.gitignore"

pipeline:
  logRunningCommand: true
