/// <reference types="vite/client" />

// Sync WASM module declarations (generated by transpiler with --sync flag)
// These are used as fallback for browsers without JSPI support (Safari)
declare module '../../../../packages/wasm-tsx/wasm-sync/tsx-engine.js' {
    export const command: {
        run: (name: string, args: string[], env: { cwd: string; vars: [string, string][] }, stdin: unknown, stdout: unknown, stderr: unknown) => number;
        listCommands: () => string[];
    };
    export const $init: Promise<void> | undefined;
}

declare module '../../../../packages/wasm-sqlite/wasm-sync/sqlite-module.js' {
    export const command: {
        run: (name: string, args: string[], env: { cwd: string; vars: [string, string][] }, stdin: unknown, stdout: unknown, stderr: unknown) => number;
        listCommands: () => string[];
    };
    export const $init: Promise<void> | undefined;
}
