#!/bin/bash
# generate-wasm-imports.sh
# Extracts imports from ALL WASM files and generates Swift manifest for compile-time validation
#
# This script runs as an Xcode Build Phase before compilation.
# It generates GeneratedWASMImports.swift containing all required imports.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
WASM_DIR="$PROJECT_DIR/EdgeAgent/Resources/WebRuntime"
OUTPUT_FILE="$PROJECT_DIR/EdgeAgent/Bridge/GeneratedWASMImports.swift"

# Require wasm-tools
if ! command -v wasm-tools &> /dev/null; then
    echo "error: wasm-tools not found. Install with: cargo install wasm-tools"
    exit 1
fi

# Function to extract imports from a WASM file
extract_imports() {
    local wasm_file="$1"
    
    # Parse imports: (import "module" "name" (func ...))
    wasm-tools print "$wasm_file" 2>/dev/null | \
        grep -E '^\s*\(import' | \
        sed -E 's/.*\(import "([^"]+)" "([^"]+)".*/\1.\2/' | \
        sort | uniq
}

# Convert path to Swift enum name (e.g., "mcp-server-sync/ts-runtime-mcp.core.wasm" -> "McpServerSyncTsRuntimeMcpCore")
to_enum_name() {
    local filepath="$1"
    # Remove .wasm, replace special chars with space, capitalize words, remove spaces
    echo "$filepath" | \
        sed 's/\.wasm$//' | \
        tr '/-.' ' ' | \
        awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1' | \
        tr -d ' '
}

# Start generating Swift file
cat > "$OUTPUT_FILE" << 'HEADER'
// GeneratedWASMImports.swift
// AUTO-GENERATED - DO NOT EDIT
// Generated by generate-wasm-imports.sh from WASM files
//
// This file provides compile-time constants for validating provider import coverage.

import Foundation

HEADER

# Find all .wasm files and generate imports for each
# Use relative paths to create unique enum names
cd "$WASM_DIR"
find . -name "*.wasm" -type f 2>/dev/null | sed 's|^\./||' | sort -u | while read -r rel_path; do
    wasm_file="$WASM_DIR/$rel_path"
    enum_name=$(to_enum_name "$rel_path")
    
    echo "// Extracting imports from $rel_path..."
    
    # Generate enum for this WASM file
    cat >> "$OUTPUT_FILE" << EOF
/// Required imports for $rel_path
public enum ${enum_name}WASMImports {
    /// All imports required by $rel_path
    public static let required: Set<String> = [
EOF
    
    extract_imports "$wasm_file" | while read -r import; do
        echo "        \"$import\"," >> "$OUTPUT_FILE"
    done
    
    echo "    ]" >> "$OUTPUT_FILE"
    echo "}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

# Generate the AllWASMImports enum that combines all imports
echo "" >> "$OUTPUT_FILE"
cat >> "$OUTPUT_FILE" << 'EOF'
/// All WASM modules and their combined required imports
public enum AllWASMImports {
    /// Combined set of all imports required by any WASM module
    public static var allRequired: Set<String> {
        var all = Set<String>()
EOF

# Add all enum references
cd "$WASM_DIR"
find . -name "*.wasm" -type f 2>/dev/null | sed 's|^\./||' | sort -u | while read -r rel_path; do
    enum_name=$(to_enum_name "$rel_path")
    echo "        all.formUnion(${enum_name}WASMImports.required)" >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" << 'EOF'
        return all
    }
}
EOF

echo "Generated $OUTPUT_FILE"
