#!/bin/bash
# generate-wasm-imports.sh
# Extracts imports from WASM files and generates Swift manifest for compile-time validation
#
# This script runs as an Xcode Build Phase before compilation.
# It generates GeneratedWASMImports.swift containing all required imports.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
WASM_DIR="$PROJECT_DIR/EdgeAgent/Resources/WebRuntime"
OUTPUT_FILE="$PROJECT_DIR/EdgeAgent/Bridge/GeneratedWASMImports.swift"

# Require wasm-tools
if ! command -v wasm-tools &> /dev/null; then
    echo "error: wasm-tools not found. Install with: cargo install wasm-tools"
    exit 1
fi

# Function to extract imports from a WASM file
extract_imports() {
    local wasm_file="$1"
    local var_name="$2"
    
    # Parse imports: (import "module" "name" (func ...))
    wasm-tools print "$wasm_file" 2>/dev/null | \
        grep -E '^\s*\(import' | \
        sed -E 's/.*\(import "([^"]+)" "([^"]+)".*/\1.\2/' | \
        sort | uniq
}

# Start generating Swift file
cat > "$OUTPUT_FILE" << 'HEADER'
// GeneratedWASMImports.swift
// AUTO-GENERATED - DO NOT EDIT
// Generated by generate-wasm-imports.sh from WASM files
//
// This file provides compile-time constants for validating provider import coverage.

import Foundation

HEADER

# Generate imports for Agent WASM
AGENT_WASM="$WASM_DIR/web-headless-agent-sync/web-headless-agent-ios.core.wasm"
if [[ -f "$AGENT_WASM" ]]; then
    echo "// Extracting imports from Agent WASM..."
    cat >> "$OUTPUT_FILE" << 'EOF'
/// Required imports for the Agent WASM module
public enum AgentWASMImports {
    /// All imports required by web-headless-agent-ios.core.wasm
    public static let required: Set<String> = [
EOF
    
    extract_imports "$AGENT_WASM" | while read -r import; do
        echo "        \"$import\"," >> "$OUTPUT_FILE"
    done
    
    echo "    ]" >> "$OUTPUT_FILE"
    echo "}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Generate imports for MCP Server WASM
MCP_WASM="$WASM_DIR/mcp-server-sync/ts-runtime-mcp.core.wasm"
if [[ -f "$MCP_WASM" ]]; then
    echo "// Extracting imports from MCP WASM..."
    cat >> "$OUTPUT_FILE" << 'EOF'
/// Required imports for the MCP Server WASM module
public enum MCPWASMImports {
    /// All imports required by ts-runtime-mcp.core.wasm
    public static let required: Set<String> = [
EOF
    
    extract_imports "$MCP_WASM" | while read -r import; do
        echo "        \"$import\"," >> "$OUTPUT_FILE"
    done
    
    echo "    ]" >> "$OUTPUT_FILE"
    echo "}" >> "$OUTPUT_FILE"
fi

echo "Generated $OUTPUT_FILE"
